"""Voice computer-use demo: speak, and the Mac acts mid-sentence.

    whisper-stream (mic) -> WhisperSource -> Controller -> FastEngine (in process)
                         -> policy -> safety -> Executor (dry-run unless --live)

Sources:
    (default)        live microphone through whisper.cpp's whisper-stream
    --audio FILE...  audio files replayed through whisper.cpp as if spoken (FileWhisperSource)
    --say TEXT...    like --audio, with the audio generated by macOS `say -o` (no microphone)
    --text TEXT...   text replay at realistic word timing (no speech recognition)

Dry-run is the default: actions are described ("would open TextEdit"), never performed, and the
screen is simulated (`--screen sim`) so chained commands see the app they just "opened".
`--live` performs actions on the real screen and asks for Enter first.

Stop everything: ⌃⌥⎋ (control-option-escape) from any app, or Ctrl-C in this terminal.

Run `python scripts/demo.py --help` for all flags; docs/DEMO.md has the walkthrough.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
import shlex
import signal
import subprocess
import sys
import tempfile
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Callable, Sequence

from jev_local.harness.hud import ConsoleHud
from jev_local.harness.types import Action, ExecResult, HarnessConfig, TranscriptEvent

ROOT = Path(__file__).resolve().parents[1]
CKPTS = {"v1": ROOT / "models" / "jev-local-fast", "v2": ROOT / "runs" / "v2" / "jev-local-fast-v2"}
PAYLOAD_KINDS = ("type_text", "search_web", "open_url")  # wait for the phrase (URL: or a chain word)


# ---------------------------------------------------------------- memory helpers

# Headroom the demo needs before it starts (this 8 GB M1 has crashed from our workloads): the
# trained engine (torch + weights, ~0.5-0.8 GB) and whisper-stream / whisper-cli (~0.3 GB, Metal),
# plus a margin so the kill switch and Ctrl-C handling never stall in a swap storm.
NEED_ENGINE_GB = 1.5
NEED_WHISPER_GB = 0.6
NEED_MARGIN_GB = 0.4


def required_free_gb(args: argparse.Namespace) -> float:
    """RAM free (GB) the demo needs to start with these flags; 0 when nothing heavy is loaded."""
    need = 0.0
    if args.engine == "fast":
        need += NEED_ENGINE_GB
    uses_whisper = bool(args.audio or args.say) or (not args.text and not args.whisper_bin)
    if uses_whisper:
        need += NEED_WHISPER_GB
    return round(need + NEED_MARGIN_GB, 2) if need else 0.0


def ram_free_gb() -> float | None:
    """free + inactive + speculative + purgeable pages (what scripts/overnight.py calls RAM free)."""
    try:
        out = subprocess.run(["vm_stat"], capture_output=True, text=True, timeout=3).stdout
    except Exception:  # noqa: BLE001
        return None
    page = int(re.search(r"page size of (\d+)", out).group(1)) if "page size of" in out else 16384
    pages = 0
    for key in ("Pages free", "Pages inactive", "Pages speculative", "Pages purgeable"):
        m = re.search(rf"{key}:\s+(\d+)", out)
        pages += int(m.group(1)) if m else 0
    return round(pages * page / 1024**3, 2)


def rss_mb(pid: int | None = None) -> float | None:
    try:
        out = subprocess.run(["ps", "-o", "rss=", "-p", str(pid or os.getpid())], capture_output=True, text=True,
                             timeout=3).stdout.strip()
        return round(int(out) / 1024, 1) if out else None
    except Exception:  # noqa: BLE001
        return None


def memory_line(extra_pids: dict[str, int | None] | None = None) -> str:
    parts = [f"this process {rss_mb()} MB"]
    for name, pid in (extra_pids or {}).items():
        if pid:
            parts.append(f"{name} {rss_mb(pid)} MB")
    free = ram_free_gb()
    if free is not None:
        parts.append(f"RAM free {free} GB")
    return "memory: " + ", ".join(parts)


# ---------------------------------------------------------------- mid-sentence bookkeeping


@dataclass
class ActLog:
    describe: str
    kind: str
    t: float
    uid: str | None
    word_k: int
    final_seen: bool  # the utterance's final transcript had already arrived when it fired
    outcome: str
    detail: str
    dry_run: bool
    confirmed: bool = False  # executed on a spoken "confirm" (not a mid-sentence decision)


@dataclass
class UttLog:
    uid: str
    t_start: float
    text: str = ""
    n_words: int = 0
    t_last_word: float | None = None  # when the last word first appeared in a partial
    t_final: float | None = None
    t_eos: float | None = None  # end of speech (audio replay: from the waveform)
    actions: list[ActLog] = field(default_factory=list)
    decisions: list[tuple[str, float]] = field(default_factory=list)  # (verdict, engine ms)


class SessionTap:
    """Watches transcript events and executions to report *when* each action fired.

    Attached by wrapping `controller.on_event`, so it works for every source and for `replay`.
    `eos_fn(utt)` may supply the true end of speech (audio replay); otherwise it is the moment the
    utterance's last word first appeared.
    """

    def __init__(self, clock: Callable[[], float], out: Any = None, eos_fn: Callable[[UttLog], float | None] | None = None):
        self.clock = clock
        self.out = out if out is not None else sys.stderr
        self.eos_fn = eos_fn
        # What "end of speech" means in the report. Without audio it is when the last word first
        # appeared in a transcript: with whisper-stream that is the step wait plus inference
        # (~0.4-0.8 s) after the word was actually spoken, so "ms after end of speech" is understated.
        self.eos_basis = "last word first shown in the transcript"
        self._proposed: set[int] = set()
        self.utts: list[UttLog] = []
        self.by_uid: dict[str, UttLog] = {}
        self.cur: UttLog | None = None
        self._words = 0

    def proposed(self, action: Action) -> None:
        """A risky action was proposed; if it runs later, it ran on a spoken confirmation."""
        self._proposed.add(id(action))

    def attach(self, ctl: Any) -> None:
        inner = ctl.on_event

        async def on_event(ev: TranscriptEvent) -> None:
            self.event(ev)
            await inner(ev)

        ctl.on_event = on_event  # type: ignore[method-assign]

    def event(self, ev: TranscriptEvent) -> None:
        now = self.clock()
        if ev.kind == "speech_start" or (ev.kind in ("partial", "final") and ev.uid not in self.by_uid):
            if ev.uid not in self.by_uid:
                u = UttLog(ev.uid, now)
                self.utts.append(u)
                self.by_uid[ev.uid] = u
                self.cur = u
            return
        u = self.by_uid.get(ev.uid)
        if u is None:
            return
        if ev.kind == "partial":
            n = len(ev.text.split())
            if n > u.n_words:
                u.t_last_word = now
            u.n_words, u.text = n, ev.text
        elif ev.kind == "final":
            n = len(ev.text.split())
            if n > u.n_words or u.t_last_word is None:
                u.t_last_word = now
            u.n_words, u.text, u.t_final = n, ev.text, now
            self._report_final(u)

    def decision(self, verdict: str, latency_ms: float) -> None:
        if self.cur is not None:
            self.cur.decisions.append((verdict, latency_ms))

    def executed(self, action: Action, result: ExecResult) -> ActLog:
        u = self.cur
        outcome = "failed" if not result.ok else ("dry-run" if result.dry_run else "ok")
        # A confirmed action was proposed earlier ("quit textedit") and runs on a spoken "confirm".
        confirmed = id(action) in self._proposed
        a = ActLog(action.describe(), action.kind.value, self.clock(), u.uid if u else None,
                   u.n_words if u else 0, bool(u and u.t_final is not None), outcome, result.detail, result.dry_run,
                   confirmed)
        if u is not None:
            u.actions.append(a)
        return a

    def _report_final(self, u: UttLog) -> None:
        for a in u.actions:
            if not a.final_seen:
                ahead = (u.t_final or a.t) - a.t
                self._print(f"   » {a.describe} fired at word {a.word_k} of {u.n_words} "
                            f"(before the sentence ended; {ahead * 1000:.0f} ms before the final transcript)")

    def _print(self, s: str) -> None:
        try:
            self.out.write(s + "\n")
            self.out.flush()
        except Exception:  # noqa: BLE001
            pass

    # ------------------------------------------------------------ report

    def report(self) -> dict[str, Any]:
        rows = []
        lat_eos: list[float] = []
        closed_total = closed_pre = 0
        for u in self.utts:
            eos = self.eos_fn(u) if self.eos_fn else None
            eos = eos if eos is not None else u.t_last_word
            u.t_eos = eos
            acts = []
            for a in u.actions:
                rel = None if eos is None else round((a.t - eos) * 1000.0, 1)
                if rel is not None:
                    lat_eos.append(rel)
                if a.kind not in PAYLOAD_KINDS and not a.confirmed:
                    closed_total += 1
                    closed_pre += not a.final_seen
                acts.append({"action": a.describe, "kind": a.kind, "word": f"{a.word_k}/{u.n_words}",
                             "before_final": not a.final_seen, "ms_after_end_of_speech": rel,
                             "confirmed": a.confirmed, "outcome": a.outcome, "detail": a.detail})
            eng = [ms for _, ms in u.decisions if ms]
            verdicts: dict[str, int] = {}
            for v, _ in u.decisions:
                verdicts[v] = verdicts.get(v, 0) + 1
            rows.append({"uid": u.uid, "text": u.text, "n_words": u.n_words, "actions": acts, "verdicts": verdicts,
                         "final_after_end_of_speech_ms": None if (u.t_final is None or eos is None)
                         else round((u.t_final - eos) * 1000.0, 1),
                         "engine_ms_p50": round(sorted(eng)[len(eng) // 2], 1) if eng else None})
        return {"utterances": rows,
                "closed_set_actions": closed_total, "closed_set_before_final": closed_pre,
                "end_of_speech_to_action_ms": sorted(lat_eos), "end_of_speech_basis": self.eos_basis}


class DemoHud(ConsoleHud):
    """ConsoleHud plus the 'fired at word k' line and the tap bookkeeping."""

    def __init__(self, tap: SessionTap, **kw: Any):
        super().__init__(**kw)
        self.tap = tap

    def decision(self, decision: Any) -> None:
        super().decision(decision)
        try:
            self.tap.decision(decision.verdict, decision.latency_ms)
        except Exception:  # noqa: BLE001
            pass

    def pending(self, action: Action) -> None:
        super().pending(action)
        self.tap.proposed(action)

    def executed(self, action: Action, result: ExecResult) -> None:
        super().executed(action, result)
        try:
            a = self.tap.executed(action, result)
            u = self.tap.cur
            if a.final_seen:
                after = (a.t - (u.t_final or a.t)) * 1000.0 if u else 0.0
                why = "payload waits for the phrase to end" if a.kind in PAYLOAD_KINDS else "after the final transcript"
                msg = f"   » {a.describe} fired {after:.0f} ms after the final transcript ({why})"
            else:
                msg = f"   » {a.describe} fired at word {a.word_k} - you are still talking"
            self._line("fired", msg.strip(" »"), "green", bold=True)
        except Exception:  # noqa: BLE001
            pass

    def info(self, msg: str) -> None:
        try:
            self._line("info", msg, "blue")
        except Exception:  # noqa: BLE001
            pass


# ---------------------------------------------------------------- building blocks


def harness_config(step_ms: int = 500, *, dry_run: bool = True) -> HarnessConfig:
    """The HarnessConfig for a whisper-stream source with this --step-ms.

    whisper-stream changes the transcript at most once per step, so "600 ms without a new word" is
    one late window, not silence: the silence gates span two windows plus jitter, and the partial
    debounce is 0 (one partial per step, nothing to coalesce). The Controller also raises the gates
    further if whisper turns out slower than the step (Controller.thresholds)."""
    from dataclasses import replace as dc_replace

    from jev_local.harness.controller import silence_gates_for

    cfg = HarnessConfig(dry_run=dry_run)
    payload, complete = silence_gates_for(step_ms)
    cfg.thresholds = dc_replace(cfg.thresholds, payload_silence_ms=max(payload, cfg.thresholds.payload_silence_ms),
                                silence_complete_ms=max(complete, cfg.thresholds.silence_complete_ms), debounce_ms=0)
    return cfg



def build_engines(engine: str, model: str, device: str) -> tuple[dict[str, Any], str]:
    """Returns (engines, model id for DecisionClient)."""
    if engine == "rule":
        from jev_local.harness.fakes import RuleModel, ScriptedEngine

        return {"fast": ScriptedEngine(RuleModel())}, "jev-local-fast"
    if engine == "heuristic":
        from jev_local.engine.heuristic import HeuristicEngine

        return {"heuristic": HeuristicEngine()}, "jev-local-heuristic"
    import torch

    from jev_local.engine.encoder.engine import FastEngine

    ckpt = CKPTS[model]
    if not (ckpt / "heads.safetensors").exists():
        raise SystemExit(f"checkpoint missing: {ckpt}")
    torch.set_num_threads(max(1, min(4, os.cpu_count() or 4)))
    eng = FastEngine(ckpt, device=device, dtype=torch.float16 if device == "mps" else torch.float32)
    return {"fast": eng}, "jev-local-fast"


async def warm(client: Any, app_names: Sequence[str], snap: Any, n: int = 3) -> list[float]:
    """A few real harness decisions, so the first spoken command is not the cold one."""
    from jev_local.harness.questions import build_questions, rank_apps
    from jev_local.harness.spans import extract_text_candidates, extract_url_candidates
    from jev_local.harness.state import build_state

    times = []
    for text in ("open notes", "open textedit and type hello world", "scroll down a bit")[:n]:
        apps = rank_apps(text, list(app_names), running=[], max_n=24)
        state = build_state(text, snap, [], None)
        qs = build_questions(snap, apps, extract_text_candidates(text), extract_url_candidates(text), 60)
        t0 = time.perf_counter()
        await client.system_one(state, qs)
        times.append(round((time.perf_counter() - t0) * 1000.0, 1))
    return times


def say_to_files(texts: Sequence[str], workdir: Path, voice: str | None = None, rate: int = 180) -> list[Path]:
    """macOS text-to-speech into AIFF files (no microphone, nothing on screen)."""
    out = []
    for i, t in enumerate(texts):
        p = workdir / f"say{i:02d}.aiff"
        cmd = ["say", "-o", str(p), "-r", str(rate), *(["-v", voice] if voice else []), t]
        subprocess.run(cmd, check=True, capture_output=True, timeout=60)
        out.append(p)
    return out


# ---------------------------------------------------------------- main


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    ap = argparse.ArgumentParser(prog="demo", description="Voice computer-use demo (dry-run unless --live).")
    ap.add_argument("--live", action="store_true", help="really perform actions on this Mac (default: dry-run)")
    ap.add_argument("--yes", action="store_true", help="with --live: skip the press-Enter safety prompt")
    ap.add_argument("--model", choices=sorted(CKPTS), default="v1", help="v1 = 32M computer-use specialist (default)")
    ap.add_argument("--device", choices=["cpu", "mps"], default="cpu",
                    help="engine device (default cpu: whisper already uses the GPU)")
    ap.add_argument("--engine", choices=["fast", "heuristic", "rule"], default="fast",
                    help="fast = the trained model; rule/heuristic = no-weights stand-ins for pipeline checks")
    ap.add_argument("--whisper-model", default="base.en", help="base.en (default) | small.en | path to a ggml .bin")
    ap.add_argument("--text", action="append", default=[], help="text replay (repeat for several utterances)")
    ap.add_argument("--audio", action="append", default=[], help="audio file replay (repeatable)")
    ap.add_argument("--say", action="append", default=[], help="generate audio with `say -o` and replay it (repeatable)")
    ap.add_argument("--screen", choices=["sim", "real"], default=None,
                    help="sim = simulated screen that follows dry-run actions (dry-run default); real = Accessibility")
    ap.add_argument("--word-ms", type=int, default=300, help="text replay: ms per word (default 300 = 200 wpm)")
    ap.add_argument("--pause-ms", type=int, default=1800, help="text replay: silence between utterances")
    ap.add_argument("--step-ms", type=int, default=500)
    ap.add_argument("--length-ms", type=int, default=8000)
    ap.add_argument("--keep-ms", type=int, default=200)
    ap.add_argument("--threads", type=int, default=4, help="whisper threads")
    ap.add_argument("--capture", type=int, default=-1, help="whisper-stream capture device id")
    ap.add_argument("--no-gpu", action="store_true", help="whisper on CPU only")
    ap.add_argument("--whisper-bin", default=None, help=argparse.SUPPRESS)  # tests: a fake whisper-stream command
    ap.add_argument("--no-warm", action="store_true")
    ap.add_argument("--report", type=Path, default=None, help="write a JSON report here")
    ap.add_argument("--no-log", action="store_true", help="don't write the audit log (~/.jev-local/log)")
    ap.add_argument("--no-killswitch", action="store_true",
                    help="Ctrl-C only (no control-option-escape listener; not allowed with --live)")
    ap.add_argument("--ignore-memory", action="store_true", help="start even when RAM free is below what this run needs")
    ap.add_argument("--quiet-waits", action="store_true", default=True)
    a = ap.parse_args(argv)
    if a.screen is None:
        a.screen = "real" if a.live else "sim"
    if a.live and a.screen == "sim":
        ap.error("--live needs --screen real")
    if a.live and a.no_killswitch:
        ap.error("--live needs the control-option-escape kill switch (drop --no-killswitch)")
    if sum(map(bool, (a.text, a.audio or a.say))) > 1:
        ap.error("use either --text or --audio/--say")
    return a


def _make_world(args: argparse.Namespace, cfg: HarnessConfig) -> tuple[Any, Any, Callable[[], Sequence[str]] | None]:
    from jev_local.harness.execute import Executor

    if args.screen == "sim":
        from jev_local.harness.simworld import SimExecutor, SimWorld

        world = SimWorld()
        return world, SimExecutor(Executor(world, cfg), world), world.running_apps
    from jev_local.harness import apps
    from jev_local.harness.observe import Observer

    obs = Observer(max_elements=cfg.max_elements)
    return obs, Executor(obs, cfg), apps.running_apps


async def amain(args: argparse.Namespace) -> dict[str, Any]:
    from jev_local.harness.killswitch import KillSwitch

    loop = asyncio.get_running_loop()
    clock = loop.time
    mode = "text" if args.text else ("audio" if (args.audio or args.say) else "mic")
    tap = SessionTap(clock)
    hud = DemoHud(tap, clock=clock, quiet_waits=args.quiet_waits, width=110)
    hud.info(f"jev-local demo: source={mode}, {'LIVE' if args.live else 'dry-run'}, screen={args.screen}, "
             f"engine={args.engine}/{args.model}/{args.device}")
    hud.info(memory_line())

    holder: dict[str, Any] = {}
    stop = asyncio.Event()

    def kill(why: str) -> None:
        ctl = holder.get("ctl")
        if ctl is not None:
            ctl.halt()  # latched: nothing already in the pipe can run any more
        src = holder.get("source")
        if src is not None and hasattr(src, "kill_now"):
            src.kill_now()
        hud.error(f"STOP ({why}): cancelled everything")
        stop.set()

    # Kill switch and signal handlers first, so a stop during transcription or model loading also
    # kills whisper-cli / whisper-stream.
    switch = KillSwitch(lambda: loop.call_soon_threadsafe(kill, "control-option-escape"))
    ks_mode = "off" if args.no_killswitch else switch.start()
    if args.live and ks_mode not in ("tap", "poll"):
        # In live mode the driven app is in front, so Ctrl-C in this terminal is out of reach.
        switch.stop()
        raise SystemExit("refusing --live: the global control-option-escape kill switch is not running "
                         f"({ks_mode or 'disabled'}); it is the only way to stop live control from another app. "
                         "Install pyobjc (Quartz) and don't pass --no-killswitch.")
    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            loop.add_signal_handler(sig, kill, sig.name)
        except (NotImplementedError, RuntimeError):
            pass
    hud.info(f"kill switch: control-option-escape ({ks_mode}) or Ctrl-C")
    try:
        return await _amain(args, clock, mode, tap, hud, holder, stop)
    finally:
        switch.stop()
        for sig in (signal.SIGINT, signal.SIGTERM):
            try:
                loop.remove_signal_handler(sig)
            except Exception:  # noqa: BLE001
                pass


async def _amain(args: argparse.Namespace, clock: Callable[[], float], mode: str, tap: SessionTap, hud: DemoHud,
                 holder: dict[str, Any], stop: asyncio.Event) -> dict[str, Any]:
    from jev_local.harness.client import DecisionClient
    from jev_local.harness.controller import Controller
    from jev_local.harness.log import AuditLog

    # 1. Speech source. Audio replay transcribes up front (whisper-cli exits before the model loads).
    from jev_local.harness import whisper_source as ws

    source: Any = None
    tmp = Path(tempfile.mkdtemp(prefix="jev-demo-"))
    if mode == "audio" or (mode == "mic" and not args.whisper_bin):
        wm = ws.model_path(args.whisper_model)
        if not wm.exists():
            raise SystemExit(f"whisper model missing: {wm}\n  see docs/DEMO.md (one-time setup)")
    if mode == "audio":
        files = [Path(f) for f in args.audio] + say_to_files(args.say, tmp)
        source = ws.FileWhisperSource(files, args.whisper_model, step_ms=args.step_ms, length_ms=args.length_ms,
                                      keep_ms=args.keep_ms, threads=args.threads, use_gpu=not args.no_gpu, clock=clock,
                                      workdir=tmp)
        holder["source"] = source
        tap.eos_basis = "end of the audio file's speech (waveform)"
        hud.info(f"transcribing {len(files)} file(s) with whisper-cli as whisper-stream would (step {args.step_ms} ms)...")
        try:
            await asyncio.to_thread(source.prepare)
        except Exception:
            if stop.is_set():  # killed while whisper-cli was transcribing (kill_now killed it)
                raise SystemExit("stopped while transcribing") from None
            raise
        fi = source.info
        slow = "" if fi.per_window_ms <= args.step_ms else (
            f"  WARNING: slower than real time - whisper-stream would drop {fi.dropped_s:.1f}s of audio (replayed that way)")
        hud.info(f"whisper: {fi.n_windows} windows in {fi.whisper_s:.1f}s -> {fi.per_window_ms:.0f} ms per window "
                 f"(load {fi.load_ms or 0:.0f} ms){slow}")

        def eos_fn(u: UttLog) -> float | None:
            if fi.t0 is None:
                return None
            ends = [fi.t0 + e for s, e in fi.file_spans if fi.t0 + s <= u.t_start]
            return ends[-1] if ends else None

        tap.eos_fn = eos_fn
    elif mode == "mic":
        ws.kill_stale()
        extra: dict[str, Any] = {"binary": shlex.split(args.whisper_bin), "pidfile": None} if args.whisper_bin else {}
        source = ws.WhisperSource(args.whisper_model, **extra, step_ms=args.step_ms, length_ms=args.length_ms,
                                  keep_ms=args.keep_ms, threads=args.threads, capture_id=args.capture,
                                  use_gpu=not args.no_gpu, clock=clock)
        holder["source"] = source
        tap.eos_basis = ("when whisper first printed the last word (the word was spoken ~0.4-0.8 s earlier: "
                         "step wait + inference)")

    # 2. Engine, warm-up.
    cfg = harness_config(args.step_ms, dry_run=not args.live) if mode != "text" else HarnessConfig(dry_run=not args.live)
    t0 = time.perf_counter()
    engines, model_id = await asyncio.to_thread(build_engines, args.engine, args.model, args.device)
    cfg.model = model_id
    client = DecisionClient("inproc", engines, model=model_id)
    hud.info(f"engine loaded in {time.perf_counter() - t0:.1f}s; {memory_line()}")
    observer, executor, running = _make_world(args, cfg)
    try:
        from jev_local.harness import apps

        app_names = apps.installed_apps() or None
    except Exception:  # noqa: BLE001
        app_names = None
    if not args.no_warm:
        snap = await asyncio.to_thread(observer.snapshot)
        times = await warm(client, app_names or ["Notes", "TextEdit", "Safari"], snap)
        hud.info(f"warm-up decisions: {times} ms")

    log = AuditLog(redact=cfg.log_redact, enabled=not args.no_log)
    kw: dict[str, Any] = {"log": log, "running_apps": running}
    if app_names:
        kw["app_names"] = app_names

    def factory(clk: Callable[[], float]) -> Controller:
        ctl = Controller(source, observer, client, executor, cfg, hud=hud, clock=clk, **kw)
        tap.attach(ctl)
        holder["ctl"] = ctl
        return ctl

    if stop.is_set():
        raise SystemExit("stopped before the session started")

    result: dict[str, Any] = {"mode": mode, "live": args.live, "engine": args.engine, "model": args.model,
                              "device": args.device, "whisper_model": args.whisper_model}
    try:
        if mode == "text":
            from jev_local.harness.replay import ReplayUtterance, replay

            script = [ReplayUtterance(t) for t in args.text]
            task = asyncio.ensure_future(replay(script, factory, word_ms=args.word_ms, final_delay_ms=500,
                                                pause_ms=args.pause_ms))
            stopper = asyncio.ensure_future(stop.wait())
            done, _ = await asyncio.wait({task, stopper}, return_when=asyncio.FIRST_COMPLETED)
            stopper.cancel()
            if task in done:
                rep = task.result()
                result["replay_summary"] = rep.summary()
                print("\n" + rep.table(), file=sys.stderr)
            else:
                task.cancel()
        else:
            ctl = factory(clock)
            if mode == "mic":
                hud.info("starting whisper-stream (microphone)... speak when you see 'listening'")

                async def ready_watch() -> None:
                    while source.info.ready_at is None and not stop.is_set():
                        await asyncio.sleep(0.05)
                    if source.info.ready_at is not None:
                        hud.info(f"listening (whisper ready in {source.info.ready_at - source.info.started_at:.1f}s); "
                                 + memory_line({"whisper-stream": source.info.pid}))

                watcher = asyncio.ensure_future(ready_watch())
            run = asyncio.ensure_future(ctl.run())
            stopper = asyncio.ensure_future(stop.wait())
            await asyncio.wait({run, stopper}, return_when=asyncio.FIRST_COMPLETED)
            if not run.done():
                await source.stop()
                try:
                    await asyncio.wait_for(run, 3.0)
                except (asyncio.TimeoutError, asyncio.CancelledError):
                    run.cancel()
            else:
                run.result()
                # let silence timers / pending work settle
                for _ in range(40):
                    if ctl.idle():
                        break
                    await asyncio.sleep(0.05)
            stopper.cancel()
            if mode == "mic":
                watcher.cancel()
                result["whisper_dropped_windows"] = source.info.dropped_audio
            result["stats"] = dict(ctl.stats)
            result["halted"] = ctl.halted
            result["revisions_after_act"] = len(ctl.stream.revisions)
            result["source"] = {k: v for k, v in asdict(source.stats).items()}
            if mode == "audio":
                fi = source.info
                result["whisper"] = {"n_windows": fi.n_windows, "per_window_ms": fi.per_window_ms,
                                     "batch_s": round(fi.whisper_s, 2), "load_ms": fi.load_ms,
                                     "file_spans": fi.file_spans,
                                     "windows": fi.windows}
    finally:
        if source is not None and mode == "mic":
            await source.stop()
        import shutil

        shutil.rmtree(tmp, ignore_errors=True)
    result["tap"] = tap.report()
    result["memory"] = memory_line()
    hud.info(result["memory"])
    _print_summary(result)
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(result, indent=1, default=str))
        hud.info(f"report: {args.report}")
    return result


def _print_summary(result: dict[str, Any]) -> None:
    rep = result["tap"]
    lines = ["", "== what happened =="]
    for u in rep["utterances"]:
        lines.append(f'"{u["text"]}"  ({u["n_words"]} words; verdicts {u["verdicts"]}; engine p50 {u["engine_ms_p50"]} ms)')
        if not u["actions"]:
            lines.append("    nothing executed")
        for a in u["actions"]:
            when = "BEFORE the sentence ended" if a["before_final"] else "after the final"
            rel = a["ms_after_end_of_speech"]
            rel_s = "" if rel is None else f", {rel:+.0f} ms vs end of speech"
            lines.append(f"    {a['action']}: word {a['word']}, {when}{rel_s} [{a['outcome']}]")
    lines.append(f"closed-set actions before the final transcript: {rep['closed_set_before_final']}/{rep['closed_set_actions']}")
    print("\n".join(lines), file=sys.stderr)


def preflight(args: argparse.Namespace) -> None:
    """Refuse to start when it isn't safe: too little memory, or live control nobody explicitly started."""
    need = required_free_gb(args)
    free = ram_free_gb()
    if need and free is not None and free < need and not args.ignore_memory:
        raise SystemExit(f"refusing to start: {free:.1f} GB RAM free, this run needs about {need:.1f} GB "
                         f"(engine={args.engine}). Close Chrome or other large apps and try again "
                         "(--ignore-memory overrides).")
    if args.live and not args.yes:
        if not sys.stdin or not sys.stdin.isatty():
            raise SystemExit("refusing --live: stdin is not an interactive terminal, so nobody can press Enter "
                             "to start (pass --yes only if you are at the keyboard)")
        print("\n  LIVE MODE: spoken commands will really control this Mac.\n"
              "  Risky actions (quit, close, delete, send...) still ask you to say 'confirm'.\n"
              "  Stop at any time with control-option-escape or Ctrl-C.\n  Press Enter to start (Ctrl-C to abort) ",
              end="", file=sys.stderr, flush=True)
        line = sys.stdin.readline()
        if not line.endswith("\n"):  # end of input, not a key press
            raise SystemExit("refusing --live: no Enter key press (end of input)")


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    preflight(args)
    try:
        asyncio.run(amain(args))
    except KeyboardInterrupt:
        return 130
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
