// Build everything (on the VM; never on the Mac):
//   node build.mjs              world bundle, harness, every app
//   node build.mjs app1,app2    only these apps (plus world + harness)
// Apps import "@genclass/runtime" (+ /react /redux /zustand) from packages/runtime/src: the same code as the
// published package, bundled by esbuild (onnxruntime-web is stubbed: the harness never loads the model).

import * as esbuild from "esbuild";
import sveltePlugin from "esbuild-svelte";
import { existsSync, mkdirSync, readdirSync, writeFileSync, readFileSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const RT = resolve(ROOT, "../packages/runtime/src");
const DIST = join(ROOT, "dist");
const OSS = process.env.RW_OSS_DIR ?? resolve(process.env.HOME ?? "/tmp", "gcl/real-cache/oss");
const only = process.argv[2]?.split(",").filter(Boolean);

// 1. app registry
const appDirs = readdirSync(join(ROOT, "apps")).filter((d) => !d.startsWith("_") && existsSync(join(ROOT, "apps", d, "manifest.ts")));
const gen = [
  "// Generated by build.mjs: every app manifest.",
  'import type { AppManifest } from "../shared/manifest.js";',
  ...appDirs.map((d, i) => `import m${i} from "../../apps/${d}/manifest.js";`),
  `export const APPS: AppManifest[] = [${appDirs.map((_, i) => `m${i}`).join(", ")}];`,
  "",
].join("\n");
writeFileSync(join(ROOT, "src/harness/apps.gen.ts"), gen);

// 2. world (IIFE injected as an init script)
await esbuild.build({ entryPoints: [join(ROOT, "src/world/index.ts")], bundle: true, format: "iife", platform: "browser", target: "es2022", outfile: join(DIST, "world.js"), logLevel: "warning" });

// 3. harness (node)
await esbuild.build({
  entryPoints: ["gen", "worker", "debug", "audit", "evalset"].filter((e) => existsSync(join(ROOT, `src/harness/${e}.ts`))).map((e) => join(ROOT, `src/harness/${e}.ts`)),
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node22",
  outdir: join(DIST, "harness"),
  splitting: true,
  external: ["playwright", "playwright-core"],
  banner: { js: "import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);" },
  logLevel: "warning",
});
await esbuild.build({ entryPoints: [join(ROOT, "src/harness/apps.gen.ts")], bundle: true, format: "esm", platform: "node", target: "node22", outfile: join(DIST, "manifests.mjs"), logLevel: "warning" });
const { APPS } = await import(join(DIST, "manifests.mjs") + `?t=${Date.now()}`);

// 4. apps
const stub = join(ROOT, "apps/_shared/onnx-stub.ts");
const results = [];
for (const m of APPS) {
  if (only && !only.includes(m.name)) continue;
  const b = m.build ?? {};
  if (b.vite) {
    results.push(`${m.name}: built by corpus/prepare_oss.sh (vite)${existsSync(join(DIST, "apps", m.name, "index.html")) ? "" : " — NOT BUILT YET"}`);
    continue;
  }
  const srcDir = m.source?.dir ? join(OSS, m.source.dir) : join(ROOT, "apps", m.name);
  const entry = join(srcDir, m.entry);
  const out = join(DIST, "apps", m.name);
  mkdirSync(out, { recursive: true });
  const nodePaths = [join(srcDir, "node_modules"), join(ROOT, "node_modules")].filter((p) => existsSync(p));
  const alias = {
    "@genclass/runtime/react": join(RT, "adapters/react.ts"),
    "@genclass/runtime/redux": join(RT, "adapters/redux.ts"),
    "@genclass/runtime/zustand": join(RT, "adapters/zustand.ts"),
    "@genclass/runtime": join(RT, "index.ts"),
    "@realapps/genclass": join(ROOT, "apps/_shared/genclass.ts"),
    "onnxruntime-web/webgpu": stub,
    "onnxruntime-web/wasm": stub,
    "onnxruntime-web": stub,
    ...(b.vueCompiler ? { vue: "vue/dist/vue.esm-bundler.js" } : {}),
    ...(b.alias ?? {}),
  };
  const plugins = [];
  if (b.svelte) plugins.push(sveltePlugin({ compilerOptions: { css: "injected" } }));
  const jsx = b.jsx ?? (m.framework === "preact" ? "preact" : "react");
  const t0 = Date.now();
  try {
    await esbuild.build({
      entryPoints: [entry],
      bundle: true,
      format: "esm",
      platform: "browser",
      target: "es2022",
      outfile: join(out, "bundle.js"),
      nodePaths,
      alias,
      plugins,
      conditions: ["browser", "import", "module", "default"],
      mainFields: ["browser", "module", "main"],
      jsx: b.jsxMode ?? "automatic",
      ...(b.jsxMode === "transform" ? {} : { jsxImportSource: jsx === "preact" ? "preact" : "react" }),
      loader: { ".js": b.jsxInJs ? "jsx" : "js", ".svg": "text", ".css": "empty", ".scss": "empty", ".png": "empty", ...(b.loader ?? {}) },
      define: {
        "process.env.NODE_ENV": '"production"',
        __VUE_OPTIONS_API__: "true",
        __VUE_PROD_DEVTOOLS__: "false",
        __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: "false",
        "import.meta.env.BASE_URL": '"/"',
        "import.meta.env.VITE_API_HOST": '""',
        global: "globalThis",
        ...(b.define ?? {}),
      },
      logLevel: "error",
      minify: false,
      legalComments: "none",
    });
    const rootId = b.rootId ?? "app";
    const html = `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><title>${m.title}</title><meta name="viewport" content="width=device-width, initial-scale=1"></head>\n<body><div id="${rootId}"></div><script type="module" src="/bundle.js"></script></body></html>\n`;
    writeFileSync(join(out, "index.html"), html);
    results.push(`${m.name}: ${(statSync(join(out, "bundle.js")).size / 1024).toFixed(0)} KB in ${Date.now() - t0} ms`);
  } catch (e) {
    results.push(`${m.name}: BUILD FAILED ${String(e?.message ?? e).slice(0, 800)}`);
  }
}
console.log(results.join("\n"));
console.log(`built world, harness and ${results.length} apps`);
