import type { AppManifest } from "../../src/shared/manifest.js";

const captions: [string, string][] = [
  ["A brown dog catching a frisbee in a park", "img_0412.jpg"],
  ["Two cyclists riding past a red brick warehouse", "img_0417.jpg"],
  ["A bowl of ramen with a soft boiled egg", "img_0420.jpg"],
  ["Children building a sandcastle at low tide", "img_0423.jpg"],
  ["A lighthouse on a rocky cliff under storm clouds", "img_0431.jpg"],
  ["A cat sleeping on a stack of library books", "img_0436.jpg"],
  ["Commuters waiting on a snowy train platform", "img_0440.jpg"],
  ["A farmer holding a crate of tomatoes", "img_0447.jpg"],
  ["A kayak drifting on a misty mountain lake", "img_0452.jpg"],
  ["An old man playing chess in a city square", "img_0458.jpg"],
  ["A street market selling colourful spices", "img_0463.jpg"],
  ["A toddler splashing in a puddle with yellow boots", "img_0469.jpg"],
  ["A hot air balloon over a vineyard at sunrise", "img_0474.jpg"],
  ["A barista pouring latte art into a mug", "img_0480.jpg"],
  ["Firefighters spraying water on a burning shed", "img_0486.jpg"],
  ["A horse grazing beside a wooden fence", "img_0491.jpg"],
  ["A violinist performing in a subway tunnel", "img_0497.jpg"],
  ["A pile of autumn leaves next to a rake", "img_0503.jpg"],
  ["Surfers carrying boards along a foggy beach", "img_0509.jpg"],
  ["A robot vacuum stuck under a sofa", "img_0514.jpg"],
  ["A goalkeeper diving to save a penalty", "img_0518.jpg"],
  ["A row of tulips in front of a windmill", "img_0521.jpg"],
  ["A woman reading a map on a mountain trail", "img_0526.jpg"],
  ["A delivery van parked outside a bakery", "img_0530.jpg"],
  ["A parrot eating a slice of mango", "img_0535.jpg"],
  ["Students studying around a laptop in a cafe", "img_0539.jpg"],
  ["A wooden canoe tied to a dock at dusk", "img_0544.jpg"],
  ["A plate of tacos with lime wedges", "img_0548.jpg"],
];
const tasks = captions.map(([caption, image], i) => ({ id: 300 + i, caption, image, assignee: "", label: "", status: "open" }));

const manifest: AppManifest = {
  name: "jotai-labeling",
  title: "Caption QA",
  framework: "react",
  libs: ["react", "jotai", "createStore", "useAtomValue", "fetch", "rt.guard"],
  domain: "data-labeling",
  entry: "main.tsx",
  integration: "stores",
  server: {
    base: "/api",
    auth: { ttlMs: 20000, rotate: true },
    collections: [{ name: "tasks", seed: tasks, versioned: true, protected: true, filters: ["status", "assignee"], envelope: "items", pageSize: 5 }],
    counters: [{ name: "labeled", init: 1284 }],
  },
  variants: {
    refresh: ["single-flight", "concurrent"],
    claim: ["if-match", "force"],
    queue: ["cursor", "offset"],
    labelGuard: ["pending", "none"],
    counter: ["server", "local"],
  },
  affordances: [
    { id: "username", kind: "type", sel: "form.sign-in input[name=username]", values: ["maya", "theo", "rin"], weight: 0.01, mode: "replace", clear: true, requires: "form.sign-in input[name=username]", then: ["password", "signIn"] },
    { id: "password", kind: "type", sel: "form.sign-in input[name=password]", values: ["caption-qa-7"], weight: 0, mode: "replace", clear: true, followOnly: true },
    { id: "signIn", kind: "click", sel: "form.sign-in button.sign-in", weight: 0, mode: "accumulate", followOnly: true, dblclickP: 0.1, impatientP: 0.1 },
    { id: "signInAgain", kind: "click", sel: "form.sign-in button.sign-in", weight: 1, mode: "accumulate", after: ["signIn"], requires: "form.sign-in button.sign-in:not([disabled])" },
    { id: "claim", kind: "click", sel: "li.task button.claim", nth: 5, weight: 2.2, mode: "accumulate", intent: "nth", after: ["signIn"], dblclickP: 0.15, impatientP: 0.2, requires: "li.task button.claim:not([disabled])", then: ["labelClaimed"] },
    { id: "claimOnly", kind: "click", sel: "li.task button.claim", nth: 5, weight: 1, mode: "accumulate", intent: "nth", key: "claim", after: ["signIn"], dblclickP: 0.15, impatientP: 0.2, requires: "li.task button.claim:not([disabled])" },
    { id: "labelClaimed", kind: "click", sel: "li.mine .labels button", text: ["Accurate", "Partly", "Wrong"], weight: 0, mode: "accumulate", key: "label", followOnly: true, dblclickP: 0.2, impatientP: 0.2 },
    { id: "label", kind: "click", sel: "li.mine .labels button", text: ["Accurate", "Partly", "Wrong"], nth: 3, weight: 1, mode: "accumulate", intent: "nth", key: "label", after: ["signIn"], dblclickP: 0.2, impatientP: 0.2, requires: "li.mine .labels button" },
    { id: "skip", kind: "click", sel: "li.mine button.skip", nth: 3, weight: 0.4, mode: "accumulate", intent: "nth", after: ["signIn"], requires: "li.mine button.skip:not([disabled])" },
    { id: "loadMore", kind: "click", sel: "button.load-more", weight: 1, mode: "accumulate", after: ["signIn"], dblclickP: 0.15, impatientP: 0.15, requires: "button.load-more:not([disabled])" },
    { id: "signOut", kind: "click", sel: "button.sign-out", weight: 0.04, mode: "replace", after: ["signIn"], resets: ["signIn"], requires: "button.sign-out" },
  ],
  external: [
    { kind: "update", target: "tasks", perMin: 3, where: { status: "open" }, data: [{ assignee: "kai", status: "claimed" }, { assignee: "noor", status: "claimed" }, { assignee: "ines", status: "claimed" }] },
    { kind: "update", target: "tasks", perMin: 0.8, where: { status: "claimed", assignee: "kai" }, data: [{ assignee: "", status: "open" }] },
    {
      kind: "create",
      target: "tasks",
      perMin: 2,
      data: [
        { caption: "A pelican perched on a harbour post", image: "img_0522.jpg", assignee: "", label: "", status: "open" },
        { caption: "A chef flipping pancakes in a diner", image: "img_0527.jpg", assignee: "", label: "", status: "open" },
        { caption: "A snowboarder mid jump against blue sky", image: "img_0531.jpg", assignee: "", label: "", status: "open" },
      ],
    },
    { kind: "counter", target: "labeled", perMin: 4, by: 1 },
  ],
  weights: { "session.error": 0, "session.busy": 0.1, "board.error": 0, "board.notice": 0, "board.pending": 0.1, "board.loading": 0.1, "board.loadingMore": 0.1, "board.cursor": 0, "board.pages": 0 },
  relations: [
    { name: "no task twice in the queue", fields: ["board.queue"], check: (s) => !s.board || new Set(s.board.queue.map((t: { id: number }) => t.id)).size === s.board.queue.length },
    { name: "a task is queued or yours, not both", fields: ["board.queue", "board.mine"], check: (s) => !s.board || !s.board.queue.some((t: { id: number }) => s.board.mine.some((m: { id: number }) => m.id === t.id)) },
  ],
  errorSelector: "[role=alert]",
  sessionMs: [25000, 60000],
};
export default manifest;
